name: Automatic Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Releasing Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          output-file: 'changelog.md'
          release-count: 0
          version-file: './composer.json'

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
